Option to invert normals
JuliaGeometry/MarchingCubes.jl pull request #14
Opened 2023-01-24 16:19 UTC by nickkeepfer

Keyword argument option to invert normals if neccessary on the makemesh_GeometryBasics function.
(normals can are inverted if mesh surface is not a closed volume)

2023-01-24 16:24 UTC, t-bltg commented
What about adding a `normal_sign` attribute to the `MC` struct, and multiplying the magnitude of the normals with this sign in https://github.com/JuliaGeometry/MarchingCubes.jl/blob/93f26baa707d9a7af00ff9203a3286b939326e8f/src/MarchingCubes.jl#L629 ?

2023-01-24 16:27 UTC, nickkeepfer commented
Yep, I agree, much more succinct!

2023-01-26 17:50 UTC, t-bltg commented on src/example.jl
> +makemesh_GeometryBasics(GeometryBasics::Module, m::MC, invert_normals::Bool=false) = begin
I think this can be removed as well.

2023-01-26 17:51 UTC, nickkeepfer commented on src/example.jl
> +makemesh_GeometryBasics(GeometryBasics::Module, m::MC, invert_normals::Bool=false) = begin
Oops, good catch

2023-01-26 17:51 UTC, t-bltg commented on src/MarchingCubes.jl
> +    normal_sign::Int
Can you add a comment here, saying that `+1` corresponds to the outward pointing normal and `-1` to the inward one ?

2023-01-26 17:56 UTC, t-bltg commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
I think that computationally it would be more efficient to do the multiplication here:
https://github.com/JuliaGeometry/MarchingCubes.jl/blob/main/src/MarchingCubes.jl#L613-L615

2023-01-26 17:59 UTC, nickkeepfer commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
As in: (mag = m.normal_sign*norm(m.nrm)) > eps(F) && (m.nrm ./= mag), or on each component individually?

2023-01-26 18:11 UTC, t-bltg commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
I think (haven't checked) that `m.normal_sign * m.nrm` can allocate, but `m.normal_sign*norm(m.nrm)` is a non-allocating solution.

However, it is usually implied that the term `magnitude` is positive, so I find it confusing that it could be negative, so my preference would go to multiply each component individually ...

2023-01-26 18:13 UTC, t-bltg commented on src/MarchingCubes.jl
> +    normal_sign::Int # direction of normal vectors (+1 for outward / -1 for inward)
```suggestion
    normal_sign::Int  # direction of normal vectors (+1 for outward / -1 for inward)
```

nitpicking on the number of spaces :)

2023-01-27 11:18 UTC, nickkeepfer commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
Not sure how you want to do it for line 690, in `add_c_vertex`, 
Do you think `m.nrm .+= m.normal_sign * m.normals[n])` for each line?

2023-01-27 11:40 UTC, t-bltg commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
Good point, I haven't thought about it.

Regarding my initial comment https://github.com/JuliaGeometry/MarchingCubes.jl/pull/14#discussion_r1088185937, I was wrong: you can use `Normal(m.normal_sign * m.nrm)` everywhere, since it is non-allocating.

Tested with:
```julia
julia> using MarchingCubes, BenchmarkTools
julia>  @btime march($mc)
  8.667 ms (0 allocations: 0 bytes)
```

2023-01-27 11:43 UTC, nickkeepfer commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
In that case, do you want me to revert them all back to `Normal(m.normal_sign * m.nrm)`?

2023-01-27 11:45 UTC, t-bltg commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
Yes, exactly.
Also since the formulation `m.normal_sign * (1 - u) * ∇x(vol, i, j, k, m.nx) + u * ∇x(vol, i + 1, j, k, m.nx)` is wrong (you'd need parentheses, because of the `+` sign).

Can you add a test with the negative sign ?

Would it be possible to post an image of the example in `Makie` using the negative sign (I think we should see the shading change ...) ?

2023-01-27 11:57 UTC, t-bltg commented on src/MarchingCubes.jl
> +    push!(m.normals, Normal(m.normal_sign * m.nrm))
Not necessary, just to visually check here that everything is correct.

For the `test/` regression check, you can e.g. check that you obtain the same number of normals, and compute the `L2 norm` of `mc.normals` (it shouldn't change, compare with `≈` against the positive sign case).

Can you also add a `normal_sign ∈ (-1, +1) || throw(ArgumentError("`normal_sign` should be either -1 or +1"))` check in the constructor, and check that it throws correctly in the tests ?

2023-01-27 14:59 UTC, t-bltg commented on src/MarchingCubes.jl
> +        normal_sign::Type{G} = Int,
@nickkeepfer I see you struggle with this, I think you want `normal_sign::Int = 1,` as constructor default value.

2023-01-27 15:00 UTC, t-bltg commented on src/MarchingCubes.jl
> +            1,
And propagate here
```suggestion
            normal_sign,
```

2023-01-27 15:04 UTC, nickkeepfer commented on src/MarchingCubes.jl
> +        normal_sign::Type{G} = Int,
Yes, constructors are new to me, thank you very much, I was indeed struggling!

2023-01-27 15:06 UTC, t-bltg commented on src/MarchingCubes.jl
> +        normal_sign::Type{G} = Int,
That's how you learn ;)

2023-01-27 15:25 UTC, t-bltg commented on test/runtests.jl
> +    @test norm(m1.normals) ≈ norm(m2.normals)
You want to check that each normal has the same magnitude (they are computed in the same order, so this should be valid):
```julia
    @test all(norm.(m1.normals) .≈ norm.(m2.normals))
```

2023-01-27 15:38 UTC, nickkeepfer commented
I think (finally) I've managed to implement it successfully. This has been a good learning experience!

2023-01-27 15:40 UTC, t-bltg commented
Great, thanks, I'll leave a view comments and we should be good to go.

2023-01-27 15:44 UTC, t-bltg requested changes

2023-01-27 15:44 UTC, t-bltg commented on src/MarchingCubes.jl
> +        m.nrm[3] = m.normal_sign * (1 - u) * ∇z(vol, i, j, k, m.nz) + u * ∇z(vol, i, j, k + 1, m.nz)
```suggestion
        m.nrm[1] = (1 - u) * ∇x(vol, i, j, k, m.nx) + u * ∇x(vol, i, j, k + 1, m.nx)
        m.nrm[2] = (1 - u) * ∇y(vol, i, j, k, m.ny) + u * ∇y(vol, i, j, k + 1, m.ny)
        m.nrm[3] = (1 - u) * ∇z(vol, i, j, k, m.nz) + u * ∇z(vol, i, j, k + 1, m.nz)
```

2023-01-27 15:44 UTC, t-bltg commented on src/MarchingCubes.jl
> +        m.nrm[3] = m.normal_sign * (1 - u) * ∇z(vol, i, j, k, m.nz) + u * ∇z(vol, i, j + 1, k, m.nz)
Leftovers, to be removed
```suggestion
        m.nrm[1] = (1 - u) * ∇x(vol, i, j, k, m.nx) + u * ∇x(vol, i, j + 1, k, m.nx)
        m.nrm[2] = (1 - u) * ∇y(vol, i, j, k, m.ny) + u * ∇y(vol, i, j + 1, k, m.ny)
        m.nrm[3] = (1 - u) * ∇z(vol, i, j, k, m.nz) + u * ∇z(vol, i, j + 1, k, m.nz)
```

2023-01-27 15:44 UTC, t-bltg commented on test/runtests.jl
> +using LinearAlgebra
```suggestion

```

I'd prefer if we use `MarchingCubes.norm` instead of adding this dependency.

2023-01-27 15:44 UTC, t-bltg commented on test/runtests.jl
> +    @test_throws ArgumentError MC(dat,normal_sign=-2)
I'd prefer to be explicit about keyword arguments:
```suggestion
    @test_throws ArgumentError MC(dat; normal_sign=+2)
    @test_throws ArgumentError MC(dat; normal_sign=-2)
```

2023-01-27 15:44 UTC, t-bltg commented on src/MarchingCubes.jl
> +        m.normal_sign ∈ (-1, +1) || throw(ArgumentError("`normal_sign` should be either -1 or +1"))
This can be moved before the `m = ...` construct for early check.

```suggestion
        normal_sign ∈ (-1, +1) || throw(ArgumentError("`normal_sign` should be either -1 or +1")) 
```

2023-01-27 15:46 UTC, nickkeepfer commented on test/runtests.jl
> +using LinearAlgebra
Ahh, I didn't realise you could do that, great!

2023-01-27 15:51 UTC, t-bltg commented on Project.toml
> +LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
```suggestion
```

2023-01-27 15:51 UTC, t-bltg commented on src/MarchingCubes.jl
> +using LinearAlgebra
```suggestion

```

2023-01-27 15:52 UTC, t-bltg commented on test/runtests.jl
> +    @test all(norm.(m1.normals) .≈ norm.(m2.normals))
```suggestion
    @test all(MarchingCubes.norm.(m1.normals) .≈ MarchingCubes.norm.(m2.normals))
```

2023-01-27 17:15 UTC, t-bltg commented
Thanks for the work done here.

With CI passing, the only thing left to do is a visual check (posting an image here would be nice ;)).

2023-01-27 17:15 UTC, t-bltg approved these changes

2023-01-27 17:16 UTC, t-bltg approved these changes
Thanks for the work done here.

With CI passing, the only thing left to do is a visual check (posting an image here would be nice ;)).

2023-01-27 18:05 UTC, nickkeepfer commented
> 

Thanks for your patience! 

Heres a figure to visually check, generated via:
```julia
fig = Figure(resolution=(800,400),fontsize = 22, figure_padding=(10,10,10,10))
ax1 = Axis3(fig[1,1],title="Normal")
ax2 = Axis3(fig[1,2],title="Inverted")
dat = Float32[(x - 3)^2 + (y - 3)^2 + (z - 3)^2 for x ∈ 1:5, y ∈ 1:5, z ∈ 1:5]
m1 = MC(dat,normal_sign=1)
m2 = MC(dat,normal_sign=-1)
march(m1,5.0)
march(m2,5.0)
msh1 = MarchingCubes.makemesh(GeometryBasics, m1)
msh2 = MarchingCubes.makemesh(GeometryBasics, m2)
mesh!(ax1,msh1)
mesh!(ax2,msh2)
```

![Screenshot 2023-01-27 at 18 04 00](https://user-images.githubusercontent.com/45045579/215161497-97783bb1-6724-4093-bdcf-8a5715d34ae8.png)

2023-01-27 18:41 UTC, t-bltg commented
Great thanks.

I've checked that we have no regressions in [UnicodePlots](https://github.com/JuliaPlots/UnicodePlots.jl) (for [`isosurface`](https://github.com/JuliaPlots/UnicodePlots.jl#isosurface-plot)).

On paraview:
![pv](https://user-images.githubusercontent.com/13423344/215168483-3da737ad-a5fc-43d7-ba20-9990f00b7fd1.png)

2023-01-27 18:41 UTC, merged